### ISSUE TITLE
JSONDecodeError causes matches to stop recording

### ISSUE THREAD

**Issue by zappybiby** [xxxFRIARxxx/SaltyBot#5]
**Describe the bug**
The error `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` occurs after the program has been running for certain amount of time. I have only observed this error to happen in the middle of tournaments and exhibitions matches, not during regular matchmaking. Looking up this error, it seems this is an issue where an empty response body is returned i.e. there is no content to parse. 

**To Reproduce**
I have only observed this occurring in exhibition or tournament matches. It seems to occur regardless of how many matches are remaining. I have repeatedly encountered this error, but I am unsure exactly what is exactly the trigger for it to occur.

**Log**
```
Currently in Tournament with 3 matches remaining.  Game state is 2.
Player 2 wins!
You lost the bet.
This match has been added to the DB. There are now 924 records in the database.
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\SaltyStateMachine.py", line 33, in <module>
    the_json = my_json.get_json()
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\SaltyJson.py", line 21, in get_json
    return self.response.json()
  File "C:\Users\xxx\Downloads\saltybot\SaltyBot-main\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Current Tier is: 3
True Streaks are: (3, 2)
Current Tier is: 3
True Streaks are: (2, 3)
Current Tier is: 3
True Streaks are: (4, 2)
Current Tier is: 3
True Streaks are: (None, None)
Current Tier is: 4
True Streaks are: (None, None)
Current Tier is: None
True Streaks are: (None, None)
Current Tier is: None
True Streaks are: (None, None)
```

**Notes**
Per this [StackOverflow post](https://stackoverflow.com/a/52489159), it might be beneficial to change header to include `'Accept': 'application/json'`. That post described an issue where a request that normally returns JSON would randomly return HTML despite a successful 200 response, which may possibly be the issue here?

The other common fix I've seen involves providing the User Agent in the header to make it appear a computer is sending the request instead of the script. This program [provides ](https://github.com/xxxFRIARxxx/SaltyBot/blob/9794fc0ee2b39394a06f908330d5b9faedaf74ba/SaltyJson.py#L10)the header `{"User-Agent": "Mozilla/5.0"}` but online I have generally seen it formatted as  `{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"}`. I think this is less likely causing the issue but wanted to mention that in case it helps.

**Comment by xxxFRIARxxx** [comment]
Thanks for officially documenting yet-another #TODO.  This is something I'm going to be looking at this week, as well as the other one you'd posted.

**Comment by xxxFRIARxxx** [comment]
I've implemented the first possible fix you've detailed in your post.  Please download the latest version (1 min ago as of the writing of this message), and please let me know if you run into it again?

Thank you in advance,
Friar

**Comment by xxxFRIARxxx** [comment]
I believe the "Accept: 'application/json'" header has fixed this issue.  I ran it overnight without the JSON exploding!  

Hopefully it did, and if it did, THANK YOU!

If it didn't, feel free to reopen this ticket, and I'll take another look at it.

Thanks again!

**Comment by zappybiby** [comment]
I have not encountered this error since the fix was implemented. Occasionally the program has behaved similarly to what was seen in the above log, where it only prints the True Streaks / Current Tier. However, no error is thrown, my debugging shows that we are getting proper 200 response, I am unsure what might be causing that. I've only seen it occur in the tournament mode. Either way, it is happening less frequently, and I am now able to run continuously for several issues without issue.

**Comment by xxxFRIARxxx** [comment]
> Occasionally the program has behaved similarly to what was seen in the above log, where it will stop outputting details of matches and will only print the True Streaks / Current Tier. However, no error is thrown, my debugging shows that we are getting proper 200 JSON response, I am unsure what might be causing that.

Hmmm, this is still happening to you, even after the fix?  The fix SHOULD have been the reason why that was happening too.  (Kind of a 2-in-1 solution).

I haven't seen it just go into "Only streaks/tier printing" mode all night, and this has been running for over 12 hours without issue.

I'll leave the program running as long as it will right now to see if it'll hang.  I'll let you know when/if it does by tomorrow same time.

**Comment by zappybiby** [comment]
I found that a different error causes that exact behavior seen in the log:
```
File SaltyParser.py, line 104, in get_gameMode
if self.is_exhib() is True:
File SaltyParser.py, line 47, in is_exhib
if self.json_dict["remaining"] == None:
TypeError: 'NoneType' object is not subscriptable
```
I've encountered this error before and it appears to still occur occasionally as of the most recent commit during matchmaking mode. I wasn't in debug mode and unsure how it occurred so having difficulty reproducing.

**Comment by xxxFRIARxxx** [comment]
Hey ZB:

This happened to me today too, so I had my friend help me with some ideas.

At least now with this build I'm about to upload, when it happens in the future, we'll get the actual "piece" that's returning none instead of trying to guess.

Let me know when this pops up for you and put the info you can back into another thread below this one, and we'll get this thing buttoned up.

**Comment by zappybiby** [comment]
Both the `TypeError: 'NoneType' object is not subscriptable` and `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` errors are likely being caused by the same thing. The `state.json` returned an empty response for whatever reason. Especially given that it is the decode error is occuring on char 0, meaning it's not one of the keys/values causing the issue, but rather the entire response itself is invalid JSON as it's invalid from the very beginning.

Right now SaltyJson only considers if the request was valid (i.e. received status code 200), but it seems we can still get empty response with this code. So I think the fix here is to validate the JSON before using it.

One way we can do this is with jsonschema ([gist](https://gist.github.com/zappybiby/ac4d719a2db441869dfcfbb552a695db)], where in my example it checks if 
1. Json returned is of 'object' type (which would raise exception if dict was empty, {''}) 
2. that all required keys (p1name, p2name, etc) are present in the returned dict

Ultimately, we may not find what causes this empty response, but this should be fine as long as it remains infrequent and we validate the JSON in some way. My example will throw exception for debugging purposes but assuming its just a sporadic issue we could just have it retry get_json again.

**Comment by zappybiby** [comment]
What's confusing to me is that saltybet.com/state.json returns a content-type header of `text/html` which normally requests.json() couldn't parse. That's how the website is configured. So actually, I'm not sure our change of `"Accept": "application/json"` is doing anything. If the `state.json` isn't formatted as `application/json` content then that could definitely cause an issue parsing it.

The only way I could see this fixed, is by first converting `state.json` from HTML to JSON, even though `state.json` returns appears to be valid JSON most of the time. Otherwise, we just have to rely on checking if it is valid JSON.

**Comment by zappybiby** [comment]
Here are my considerations:
Both the `TypeError: 'NoneType' object is not subscriptable` and `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` errors are likely being caused by the same thing. The `state.json` returned an empty response for whatever reason, or there is something preceding the valid JSON that makes the entire JSON invalid. JSONDecodeError failing on char 0 means that this isn't an issue with an invalid key/value structure, but rather the entire response as a whole is invalid. 

The saltybet.com/state.json has a content-type of text/html. It [does not appear to have support](https://ibb.co/VVCV15d) 'accept application/json'. 

I think this should work:
1. Check for empty response: [gist](https://gist.github.com/zappybiby/ac4d719a2db441869dfcfbb552a695db)

**Comment by zappybiby** [comment]
Using current commit of your repo, return of response appears to be empty when JSONDecodeError is caught in try-catch block of SaltyJson:
```
except requests.exceptions.JSONDecodeError:
    time.sleep(1)
    print("content:", self.response.text)
    return self.get_json()
```
returns
```
content:
```

**Comment by xxxFRIARxxx** [comment]
I've had no crashes in 1000 matches, and I'm wondering why the JSON was still failing for you??  Hmmm...

I don't know what to do now, B/C I don't really need the pull request for this, but you do?

I'm going to leave this open to think about it for a bit.

**Comment by FuzzyRamen** [comment]
Hi,

First off, cool bot. Been testing/following for about ~2 weeks. And I am definitely not a coder.

From my experience of monitoring, the problem seems to be the transition from exhibition to matchmaking based on where the error begins or sometimes when a match crashes now. Today I had the one with the JSON error (around 1AM EST) and then one without the JSON error (around 6:30 EST) with it just spams True Streaks using the new implementation.

**Comment by zappybiby** [comment]
It's your call. What has 100% worked for me is adding the below to SaltyStateMachine. This handled the blank response and retried after 1 second successfully, continuing to record matches without interruption. My attempts at catching an empty response in SaltyJson have not been successful. It's strange, because JSONDecodeError should throw when it attempts to return json

```
while True:
    the_json = my_json.get_json()
    if not the_json:
        print("JSON Returned Empty, retrying...")
        time.sleep(1)
        continue
    else:
        my_parser = SaltyJsonParser(the_json)
        ...
```

I have run your code without the above addition for several hours, sometimes up to a day, without issue, then sometimes I will have two blank responses in an hour. It's very random, and I think its a server-sided issue. I do think it would be best to have some form of verification of the returned JSON added to your code, because the program is dependent on valid JSON to perform all of its functions. If a blank response is returned, it stops recording matches. 

Per stackoverflow, the two most common reasons server would produce a blank response is either it is detecting our scraper somehow (user-agent should prevent this), or that it is in response to excessive API requests. 

The website is served by Cloudflare, but doesn't seem to have a anti-scraping/anti-ddos function enabled. Normally, Cloudflare limits requests to 1500 per 5 minutes, but we definitely exceed that without issue. So I'm not sure.

**Comment by zappybiby** [comment]
@FuzzyRamen Can you try https://github.com/xxxFRIARxxx/SaltyBot/pull/20 and let me know if it works for you.

**Comment by FuzzyRamen** [comment]
> @FuzzyRamen Can you try #20 and let me know if it works for you.

Will do and thanks.

**Comment by xxxFRIARxxx** [comment]
@zappybiby @FuzzyRamen Firstly, I didn't know you could @ people in this...awesome!

Secondly, I've noticed a new bug (that might also kinda be related to this), where if you START the program in exhibition mode, it never transitions out of it.  

If you start the program in any other mode besides exhibition, it works fine.  

I'll be looking into the bug I just wrote above, as well as the other bugs throughout the upcoming week.

Thanks all, and I'm glad you're enjoy SaltyBot so far.

**Comment by xxxFRIARxxx** [comment]
Merged and closed with #20
